# Generated by Django 3.1.7 on 2021-03-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_of_both',
        ),
        migrations.RemoveField(
            model_name='member',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sex',
        ),
    ]
