# Generated by Django 3.1.7 on 2021-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20210323_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='family_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
