# Generated by Django 3.1.7 on 2021-03-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20210325_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='sex',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('ND', 'Not Defined')], default='ND', max_length=2),
        ),
    ]
