# Generated by Django 3.1.7 on 2021-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_auto_20210323_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='fields_of_interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='industry_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='introduction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name_of_company_or_organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='name_of_the_institute_you_took_the_mba_emba',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_entered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_graduation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='your_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.BooleanField(null=True),
        ),
    ]
