# Generated by Django 3.1.7 on 2021-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_auto_20210324_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDegreeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, null=True)),
                ('graduated', models.BooleanField(null=True)),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('completion_status', models.BooleanField(null=True)),
                ('year_of_entered', models.IntegerField(null=True)),
                ('year_of_graduation', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MbaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, null=True)),
                ('graduated', models.BooleanField(null=True)),
                ('faculty', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('completion_status', models.BooleanField(null=True)),
                ('year_of_entered', models.IntegerField(null=True)),
                ('year_of_graduation', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='year_of_entered',
        ),
        migrations.RemoveField(
            model_name='member',
            name='year_of_graduation',
        ),
    ]
